# Generated by Django 5.0.6 on 2024-05-29 08:37

import shp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('feature', models.FileField(blank=True, upload_to='%Y/%m/%d', validators=[shp.models.validate_shp_extension])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
