# Generated by Django 5.0.3 on 2024-04-02 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shp',
            name='color',
        ),
    ]
