# Generated by Django 5.0.3 on 2024-04-02 12:01

import shp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0002_remove_shp_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shp',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='shp',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='shp',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='shp',
            name='feature',
            field=models.FileField(blank=True, upload_to='%Y/%m/%d', validators=[shp.models.validate_shp_extension]),
        ),
    ]
