# Generated by Django 5.0.3 on 2024-04-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0003_remove_shp_created_at_remove_shp_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shp',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
